
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async closeSplashscreen() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_splashscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBestMoves(id: string, engine: string, engineArgs: string[], tab: string, goMode: GoMode, options: EngineOptions) : Promise<Result<[number, BestMoves[]] | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_best_moves", { id, engine, engineArgs, tab, goMode, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Runs an isolated, bounded engine query for an interactive decision.
 * 
 * Unlike `get_best_moves`, this command returns as soon as the engine emits
 * `bestmove`. Dropping the private process on timeout also terminates the
 * engine, so callers never depend on the lifecycle of the continuous analysis
 * stream.
 */
async getBestMovesOnce(engine: string, engineArgs: string[], goMode: GoMode, options: EngineOptions, timeoutMs: number) : Promise<Result<BestMoves[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_best_moves_once", { engine, engineArgs, goMode, options, timeoutMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyzeGame(id: string, engine: string, engineArgs: string[], goMode: GoMode, options: AnalysisOptions, uciOptions: EngineOption[]) : Promise<Result<MoveAnalysis[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_game", { id, engine, engineArgs, goMode, options, uciOptions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelAnalysis(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_analysis", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopEngine(engine: string, tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_engine", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async killEngine(engine: string, tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_engine", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async killEngines(tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_engines", { tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEngineLogs(engine: string, tab: string) : Promise<Result<EngineLog[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_logs", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memorySize() : Promise<number> {
    return await TAURI_INVOKE("memory_size");
},
async getPuzzle(file: string, minRating: number, maxRating: number, theme: string | null) : Promise<Result<Puzzle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle", { file, minRating, maxRating, theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchOpeningName(query: string) : Promise<Result<OutOpening[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_opening_name", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningFromFen(fen: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_from_fen", { fen }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningFromFens(fens: string[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_from_fens", { fens }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningFromName(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_from_name", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayersGameInfo(file: string, id: number) : Promise<Result<PlayerGameInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_players_game_info", { file, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEngineConfig(path: string, args: string[]) : Promise<Result<EngineConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_config", { path, args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fileExists(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("file_exists", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileMetadata(path: string) : Promise<Result<FileMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergePlayers(file: string, player1: number, player2: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_players", { file, player1, player2 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async convertPgn(files: string[], dbPath: string, timestamp: number | null, title: string, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("convert_pgn", { files, dbPath, timestamp, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayer(file: string, id: number) : Promise<Result<Player | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player", { file, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countPgnGames(file: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_pgn_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readGames(file: string, start: number, end: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_games", { file, start, end }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lexPgn(pgn: string) : Promise<Result<Token[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lex_pgn", { pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isBmi2Compatible() : Promise<boolean> {
    return await TAURI_INVOKE("is_bmi2_compatible");
},
async deleteGame(file: string, n: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_game", { file, n }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDuplicatedGames(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_duplicated_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEmptyGames(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_empty_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearGames() : Promise<void> {
    await TAURI_INVOKE("clear_games");
},
async setFileAsExecutable(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_file_as_executable", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIndexes(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_indexes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createIndexes(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_indexes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async editDbInfo(file: string, title: string | null, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_db_info", { file, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDbGame(file: string, gameId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_db_game", { file, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeDbGame(file: string, gameId: number, pgn: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_db_game", { file, gameId, pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDatabase(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_database", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportToPgn(file: string, destFile: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_to_pgn", { file, destFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authenticate(username: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("authenticate", { username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeGame(filePath: string, n: number, pgn: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_game", { filePath, n, pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadFile(id: string, url: string, path: string, token: string | null, finalize: boolean | null, totalSize: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_file", { id, url, path, token, finalize, totalSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTournaments(file: string, query: TournamentQuery) : Promise<Result<QueryResponse<Event[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tournaments", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDbInfo(file: string) : Promise<Result<DatabaseInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_db_info", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGames(file: string, query: GameQuery) : Promise<Result<QueryResponse<NormalizedGame[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_games", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchPosition(file: string, query: GameQuery, tabId: string) : Promise<Result<[PositionStats[], NormalizedGame[]], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_position", { file, query, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryPosition(file: string, query: GameQuery, tabId: string, background: boolean) : Promise<Result<PositionSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_position", { file, query, tabId, background }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateOpeningReport(token: string, options: OpeningReportOptions, tabId: string) : Promise<Result<OpeningReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_opening_report", { token, options, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPositionGames(token: string, offset: number, limit: number, sort: PositionGameSort, direction: SortDirection, tabId: string) : Promise<Result<PositionGameMetadata[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_position_games", { token, offset, limit, sort, direction, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPositionGame(token: string, offset: number) : Promise<Result<PositionGame, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_position_game", { token, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelPositionSearch(tabId: string) : Promise<boolean> {
    return await TAURI_INVOKE("cancel_position_search", { tabId });
},
async getPlayers(file: string, query: PlayerQuery) : Promise<Result<QueryResponse<Player[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_players", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPuzzleDbInfo(file: string) : Promise<Result<PuzzleDatabaseInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_db_info", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPuzzleThemes(file: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_themes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThemesForPuzzle(file: string, puzzleId: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_themes_for_puzzle", { file, puzzleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePuzzleDatabase(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_puzzle_database", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startGame(gameId: string, config: GameConfig) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_game", { gameId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameState(gameId: string) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_state", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async makeGameMove(gameId: string, uci: string) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("make_game_move", { gameId, uci }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async takeBackGameMove(gameId: string) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_back_game_move", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resignGame(gameId: string, color: string) : Promise<Result<GameState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resign_game", { gameId, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async abortGame(gameId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_game", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameEngineLogs(gameId: string, color: string) : Promise<Result<EngineLog[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_engine_logs", { gameId, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameManifest(gameId: string) : Promise<Result<GameManifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_manifest", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startModelGameBatch(batchId: string, config: ModelGameBatchConfig) : Promise<Result<ModelGameBatchState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_model_game_batch", { batchId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelGameBatch(batchId: string) : Promise<Result<ModelGameBatchState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_game_batch", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseModelGameBatch(batchId: string) : Promise<Result<ModelGameBatchState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_model_game_batch", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeModelGameBatch(batchId: string) : Promise<Result<ModelGameBatchState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_model_game_batch", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelModelGameBatch(batchId: string) : Promise<Result<ModelGameBatchState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_model_game_batch", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelModelGameBatchesForOwner(ownerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_model_game_batches_for_owner", { ownerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dismissModelGameBatch(batchId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_model_game_batch", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startBotLeague(leagueId: string, config: BotLeagueConfig) : Promise<Result<BotLeagueState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_bot_league", { leagueId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBotLeague(leagueId: string) : Promise<Result<BotLeagueState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_bot_league", { leagueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseBotLeague(leagueId: string) : Promise<Result<BotLeagueState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_bot_league", { leagueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeBotLeague(leagueId: string) : Promise<Result<BotLeagueState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_bot_league", { leagueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelBotLeague(leagueId: string) : Promise<Result<BotLeagueState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_bot_league", { leagueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelBotLeaguesForOwner(ownerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_bot_leagues_for_owner", { ownerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dismissBotLeague(leagueId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_bot_league", { leagueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBotLeagues() : Promise<Result<BotLeagueSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_bot_leagues") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBotLeagueDetail(leagueId: string) : Promise<Result<BotLeagueDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_bot_league_detail", { leagueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readBotLeagueGame(leagueId: string, index: number) : Promise<Result<BotLeagueGameArtifact, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_bot_league_game", { leagueId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteBotLeague(leagueId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bot_league", { leagueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportBotLeague(leagueId: string, destinationDirectory: string, folderName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_bot_league", { leagueId, destinationDirectory, folderName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModelGameExperiments() : Promise<Result<ModelGameExperimentSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_model_game_experiments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelGameExperiment(experimentId: string) : Promise<Result<ModelGameExperimentDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_game_experiment", { experimentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyzeModelGameExperiment(analysisId: string, experimentId: string, engine: string, engineArgs: string[], goMode: GoMode, uciOptions: EngineOption[]) : Promise<Result<ExperimentAnalysisResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_model_game_experiment", { analysisId, experimentId, engine, engineArgs, goMode, uciOptions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelGameExperimentAnalysis(experimentId: string) : Promise<Result<ExperimentAnalysisResult | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_game_experiment_analysis", { experimentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyzeModelGameExperimentEmpiricalWdl(experimentId: string, engine: string, engineArgs: string[], goMode: GoMode, uciOptions: EngineOption[]) : Promise<Result<EmpiricalWdlResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_model_game_experiment_empirical_wdl", { experimentId, engine, engineArgs, goMode, uciOptions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelGameExperimentEmpiricalWdl(experimentId: string) : Promise<Result<EmpiricalWdlResult | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_game_experiment_empirical_wdl", { experimentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readModelGameExperimentGame(experimentId: string, index: number) : Promise<Result<ModelGameExperimentGameArtifact, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_model_game_experiment_game", { experimentId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModelGameExperiment(experimentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model_game_experiment", { experimentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportModelGameExperiment(experimentId: string, destinationDirectory: string, folderName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_model_game_experiment", { experimentId, destinationDirectory, folderName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSingleModelGameExperiment(experimentId: string, ownerId: string, gameId: string, config: GameConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_single_model_game_experiment", { experimentId, ownerId, gameId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async finalizeSingleModelGameExperiment(experimentId: string, gameId: string, cancelled: boolean) : Promise<Result<ModelGameExperimentDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finalize_single_model_game_experiment", { experimentId, gameId, cancelled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async finalizeSingleModelGameExperimentsForOwner(ownerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finalize_single_model_game_experiments_for_owner", { ownerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async preloadReferenceDb(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preload_reference_db", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProgress(id: string) : Promise<ProgressItem | null> {
    return await TAURI_INVOKE("get_progress", { id });
},
async clearProgress(id: string) : Promise<void> {
    await TAURI_INVOKE("clear_progress", { id });
},
async getManagedMaiaStatus(enginesDir: string) : Promise<Result<ManagedMaiaStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_managed_maia_status", { enginesDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installManagedMaia(id: string, enginesDir: string, repair: boolean) : Promise<Result<ManagedMaiaInstallation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_managed_maia", { id, enginesDir, repair }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelManagedMaiaInstall(id: string) : Promise<boolean> {
    return await TAURI_INVOKE("cancel_managed_maia_install", { id });
},
async uninstallManagedMaia(enginesDir: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_managed_maia", { enginesDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSoundServerPort() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sound_server_port") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
bestMovesPayload: BestMovesPayload,
botLeagueEvent: BotLeagueEvent,
clockUpdateEvent: ClockUpdateEvent,
databaseProgress: DatabaseProgress,
gameMoveEvent: GameMoveEvent,
gameOverEvent: GameOverEvent,
modelGameBatchEvent: ModelGameBatchEvent,
progressEvent: ProgressEvent
}>({
bestMovesPayload: "best-moves-payload",
botLeagueEvent: "bot-league-event",
clockUpdateEvent: "clock-update-event",
databaseProgress: "database-progress",
gameMoveEvent: "game-move-event",
gameOverEvent: "game-over-event",
modelGameBatchEvent: "model-game-batch-event",
progressEvent: "progress-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AnalysisOptions = { fen: string; moves: string[]; annotateNovelties: boolean; referenceDb: string | null; reversed: boolean }
export type BestMoves = { nodes: number; depth: number; score: Score; uciMoves: string[]; sanMoves: string[]; multipv: number; nps: number }
export type BestMovesPayload = { bestLines: BestMoves[]; engine: string; tab: string; fen: string; moves: string[]; progress: number }
export type BotLeagueConfig = { ownerId: string; players: BotLeaguePlayer[]; gamesPerPair: number; alternateColors: boolean; baseSeed: number; seedStep: number; requestedConcurrency: number; maxCpuThreads: number; maxMemoryMb: number; maxRetries: number; timeControl: TimeControl | null; openingBook: OpeningBookConfig | null }
export type BotLeagueDetail = { summary: BotLeagueSummary; config: BotLeagueConfig; results: BotLeagueGameResult[]; standings: BotLeagueStanding[] }
export type BotLeagueEvent = { state: BotLeagueState }
export type BotLeagueGameArtifact = { leagueId: string; index: number; pgn: string }
export type BotLeagueGameResult = { index: number; pairIndex: number; round: number; gameId: string; whiteProfileId: string; blackProfileId: string; whitePlayer: string; blackPlayer: string; whiteSeed: number | null; blackSeed: number | null; attempts: number; status: BotLeagueGameStatus; result: GameResult | null; plies: number; error: string | null; artifactAvailable: boolean }
export type BotLeagueGameStatus = "completed" | "failed"
export type BotLeaguePlayer = { profileId: string; name: string; targetElo: number; profileVersion: number; catalogVersion: string; config: PlayerConfig }
export type BotLeaguePlayerSummary = { profileId: string; name: string; targetElo: number; profileVersion: number; catalogVersion: string }
export type BotLeagueStanding = { profileId: string; name: string; targetElo: number; games: number; whiteGames: number; blackGames: number; wins: number; draws: number; losses: number; points: number; scorePercent: number; estimatedElo: number | null }
export type BotLeagueState = { leagueId: string; ownerId: string; status: BotLeagueStatus; totalGames: number; completedGames: number; failedGames: number; activeGames: string[]; queuedGames: number; effectiveConcurrency: number; estimatedThreadsPerGame: number; estimatedHashMbPerGame: number; results: BotLeagueGameResult[]; standings: BotLeagueStanding[] }
export type BotLeagueStatus = "running" | "paused" | "cancelling" | "completed" | "cancelled"
export type BotLeagueSummary = { leagueId: string; ownerId: string; status: BotLeagueStatus; createdAt: string; updatedAt: string; players: BotLeaguePlayerSummary[]; gamesPerPair: number; totalGames: number; completedGames: number; failedGames: number; recordedGames: number }
export type ClockUpdateEvent = { gameId: string; whiteTime: bigint | null; blackTime: bigint | null }
export type DatabaseInfo = { title: string; description: string; player_count: number; event_count: number; game_count: number; storage_size: bigint; filename: string; indexed: boolean }
export type DatabaseProgress = { id: string; progress: number }
export type DrawReason = "stalemate" | "insufficientMaterial" | "threefoldRepetition" | "fiftyMoveRule" | "agreement"
export type EmpiricalWdlCalibration = { meanAbsoluteError: number; brierScore: number }
export type EmpiricalWdlEvaluator = { engine: string; engineArgs: string[]; goMode: GoMode; uciOptions: EngineOption[] }
export type EmpiricalWdlInterval = { lower: number; upper: number }
export type EmpiricalWdlObserved = { sampleSize: number; whiteWins: number; draws: number; blackWins: number; whiteWin: number; draw: number; blackWin: number; whiteWinInterval: EmpiricalWdlInterval; drawInterval: EmpiricalWdlInterval; blackWinInterval: EmpiricalWdlInterval }
export type EmpiricalWdlPrediction = { whiteWin: number; draw: number; blackWin: number; rawWhiteWin: number; rawDraw: number; rawBlackWin: number }
export type EmpiricalWdlResult = { schemaVersion: number; experimentId: string; analyzedAt: string; initialFen: string; initialMoves: string[]; evaluator: EmpiricalWdlEvaluator; prediction: EmpiricalWdlPrediction; observed: EmpiricalWdlObserved; calibration: EmpiricalWdlCalibration }
export type EngineConfig = { name: string; options: UciOptionConfig[] }
export type EngineLaunchMetadata = { path: string; resolvedArgs: string[]; randomSeed: number | null; appliedOptions: EngineOption[]; skippedUnsupportedOptions: string[] }
export type EngineLog = { type: "gui"; value: string } | { type: "engine"; value: string }
export type EngineOption = { name: string; value: string }
export type EngineOptions = { fen: string; moves: string[]; extraOptions: EngineOption[] }
export type Event = { id: number; name: string | null }
export type ExperimentAnalysisEvaluator = { engine: string; engineArgs: string[]; goMode: GoMode; uciOptions: EngineOption[]; inaccuracyThresholdCp: number; mistakeThresholdCp: number; blunderThresholdCp: number }
export type ExperimentAnalysisGame = { index: number; gameId: string; whitePlayer: string; blackPlayer: string; result: GameResult | null; analyzedPlies: number; white: ExperimentAnalysisSideMetrics; black: ExperimentAnalysisSideMetrics; phases: ExperimentAnalysisPhaseMetrics[] }
export type ExperimentAnalysisPhaseMetrics = { phase: string; moves: number; acpl: number | null; inaccuracies: number; mistakes: number; blunders: number }
export type ExperimentAnalysisPlayerMetrics = { name: string; games: number; whiteGames: number; blackGames: number; wins: number; draws: number; losses: number; moves: number; acpl: number | null; inaccuracies: number; mistakes: number; blunders: number }
export type ExperimentAnalysisResult = { schemaVersion: number; experimentId: string; analyzedAt: string; evaluator: ExperimentAnalysisEvaluator; summary: ExperimentAnalysisSummary; games: ExperimentAnalysisGame[] }
export type ExperimentAnalysisSideMetrics = { moves: number; acpl: number | null; inaccuracies: number; mistakes: number; blunders: number }
export type ExperimentAnalysisSummary = { sampleSize: number; skippedGames: number; analyzedPlies: number; whiteWins: number; blackWins: number; draws: number; averagePlies: number | null; white: ExperimentAnalysisSideMetrics; black: ExperimentAnalysisSideMetrics; players: ExperimentAnalysisPlayerMetrics[]; phases: ExperimentAnalysisPhaseMetrics[] }
export type FileMetadata = { last_modified: number }
export type GameConfig = { white: PlayerConfig; black: PlayerConfig; whiteTimeControl: TimeControl | null; blackTimeControl: TimeControl | null; initialFen: string | null; initialMoves?: string[]; openingBook: OpeningBookConfig | null }
export type GameEndReason = "checkmate" | "timeout" | "resignation" | "abandonment"
export type GameManifest = { schemaVersion: number; applicationVersion: string; gameId: string; startedAt: string; exportedAt: string; hardware: ManifestHardware; initialFen: string; initialMoves: string[]; white: PlayerConfig; black: PlayerConfig; whiteEngineLaunch: EngineLaunchMetadata | null; blackEngineLaunch: EngineLaunchMetadata | null; whiteTimeControl: TimeControl | null; blackTimeControl: TimeControl | null; openingBook: OpeningBookConfig | null; status: GameStatus; result: GameResult | null; moves: GameMove[]; currentFen: string }
export type GameMove = { uci: string; san: string; fenAfter: string; clock: bigint | null; whiteTime: bigint | null; blackTime: bigint | null; color: string; source: GameMoveSource; thinkTimeMs: bigint | null }
export type GameMoveEvent = { gameId: string; moves: GameMove[]; fen: string; whiteTime: bigint | null; blackTime: bigint | null }
export type GameMoveSource = "human" | "engine" | "profileRepertoire" | "polyglot" | "initial"
export type GameOutcome = "Won" | "Drawn" | "Lost"
export type GameOverEvent = { gameId: string; result: GameResult; moves: GameMove[] }
export type GameQuery = { options?: QueryOptions<GameSort> | null; player1?: number | null; player2?: number | null; any_player?: number | null; game_id?: number | null; tournament_id?: number | null; start_date?: string | null; end_date?: string | null; range1?: [number, number] | null; range2?: [number, number] | null; sides?: Sides | null; outcome?: string | null; position?: PositionQueryJs | null; wanted_result?: string | null }
export type GameResult = { type: "whiteWins"; reason: GameEndReason } | { type: "blackWins"; reason: GameEndReason } | { type: "draw"; reason: DrawReason }
export type GameSort = "id" | "date" | "whiteElo" | "blackElo" | "ply_count"
export type GameState = { gameId: string; status: GameStatus; initialFen: string; moves: GameMove[]; currentFen: string; ply: number; turn: string; whiteTime: bigint | null; blackTime: bigint | null; whitePlayer: string; blackPlayer: string }
export type GameStatus = "playing" | { finished: { result: GameResult } }
export type GoMode = { t: "PlayersTime"; c: PlayersTime } | { t: "Depth"; c: number } | { t: "Time"; c: number } | { t: "Nodes"; c: number } | { t: "Infinite" }
export type HumanTimingConfig = { minThinkTimeMs: number; averageThinkTimeMs: number; maxThinkTimeMs: number; repertoireTimePercent: number }
export type ManagedMaiaInstallation = { name: string; version: string; path: string; args: string[]; elo: number; installedSizeMb: number; requiredFreeSpaceMb: number; sourceUrl: string; sourceRevision: string; modelUrl: string; modelRevision: string; modelSha256: string; license: string; pythonVersion: string; uvVersion: string }
export type ManagedMaiaStatus = { installed: boolean; needsRepair: boolean; installation: ManagedMaiaInstallation | null }
export type ManifestHardware = { operatingSystem: string; architecture: string; logicalCpus: bigint }
export type ModelGameBatchConfig = { ownerId: string; gameConfig: GameConfig; gameCount: number; alternateColors: boolean; seedStep: number; requestedConcurrency: number; maxCpuThreads: number; maxMemoryMb: number; maxRetries: number }
export type ModelGameBatchEvent = { state: ModelGameBatchState }
export type ModelGameBatchGameResult = { index: number; gameId: string; whitePlayer: string; blackPlayer: string; whiteSeed: number | null; blackSeed: number | null; attempts: number; status: ModelGameBatchGameStatus; result: GameResult | null; plies: number; error: string | null }
export type ModelGameBatchGameStatus = "completed" | "failed"
export type ModelGameBatchState = { batchId: string; ownerId: string; status: ModelGameBatchStatus; totalGames: number; completedGames: number; failedGames: number; activeGames: string[]; queuedGames: number; effectiveConcurrency: number; estimatedThreadsPerGame: number; estimatedHashMbPerGame: number; results: ModelGameBatchGameResult[] }
export type ModelGameBatchStatus = "running" | "paused" | "cancelling" | "completed" | "cancelled"
export type ModelGameExperimentDetail = { summary: ModelGameExperimentSummary; games: ModelGameExperimentGame[] }
export type ModelGameExperimentGame = { index: number; gameId: string; whitePlayer: string; blackPlayer: string; whiteSeed: number | null; blackSeed: number | null; attempts: number; status: string; result: GameResult | null; plies: number; error: string | null; artifactAvailable: boolean }
export type ModelGameExperimentGameArtifact = { experimentId: string; index: number; pgn: string }
export type ModelGameExperimentKind = "single" | "batch"
export type ModelGameExperimentStatus = "running" | "completed" | "cancelled"
export type ModelGameExperimentSummary = { experimentId: string; ownerId: string; kind: ModelGameExperimentKind; status: ModelGameExperimentStatus; createdAt: string; updatedAt: string; whitePlayer: string; blackPlayer: string; initialFen: string; totalGames: number; completedGames: number; failedGames: number; recordedGames: number }
export type MoveAnalysis = { best: BestMoves[]; novelty: boolean; is_sacrifice: boolean }
export type NormalizedGame = { id: number; fen: string; event: string; event_id: number; site: string; site_id: number; date?: string | null; time?: string | null; round?: string | null; white: string; white_id: number; white_elo?: number | null; black: string; black_id: number; black_elo?: number | null; result: Outcome; time_control?: string | null; eco?: string | null; opening?: string | null; ply_count?: number | null; moves: string }
export type OpeningBookConfig = { path: string; maxPly?: bigint }
export type OpeningLineSide = "white" | "black" | "both"
export type OpeningRepertoireConfig = { id: string; version?: number; mode?: OpeningRepertoireMode; maxPly?: number; lines?: WeightedOpeningLine[] }
export type OpeningRepertoireMode = "weighted" | "forcedLine" | "none"
export type OpeningReport = { version: number; generatedAt: string; databaseName: string; databaseGames: number; position: PositionSummary; options: OpeningReportOptions; filters: ReportFilters; statistics: ReportStatistics; years: ReportYear[]; unknownYearGames: number; eloBands: ReportEloBand[]; unknownEloGames: number; mostPlayedPlayers: ReportPlayer[]; strongestPlayers: ReportPlayer[]; playerCount: number; cohort: ReportStatistics; excludedTheoryGames: number; theory: ReportLine[]; theoryLineCount: number; displayedTheoryGames: number; moveOrders: ReportMoveOrder[]; moveOrderCount: number; transpositions: ReportTransposition[]; transpositionCount: number; elapsedMs: number; cacheHit: boolean }
export type OpeningReportOptions = { depth: number; theoryGames: number; maxLines: number; displayFen: string }
export type OutOpening = { name: string; fen: string }
export type Outcome = "1-0" | "0-1" | "1/2-1/2" | "*"
export type Player = { id: number; name: string | null; elo: number | null }
export type PlayerConfig = { type: "human"; name: string } | { type: "engine"; name: string; path: string; version?: string; presetCategory?: PlayerPresetCategory; targetElo?: number | null; seed?: number | null; args?: string[]; options?: EngineOption[]; openingRepertoire?: OpeningRepertoireConfig | null; humanTiming?: HumanTimingConfig | null; go: GoMode | null }
export type PlayerGameInfo = { site_stats_data: SiteStatsData[] }
export type PlayerPresetCategory = "custom" | "humanLike" | "limited" | "strong" | "reference"
export type PlayerQuery = { options: QueryOptions<PlayerSort>; name?: string | null; range?: [number, number] | null }
export type PlayerSort = "id" | "name" | "elo"
export type PlayersTime = { white: number; black: number; winc: number; binc: number }
export type PositionGame = { game: NormalizedGame; ply: number }
export type PositionGameMetadata = { snapshotOffset: number; id: number; white: string; black: string; whiteElo: number | null; blackElo: number | null; date: string | null; result: string; event: string; ply: number; nextMove: string }
export type PositionGameSort = "index" | "date" | "averageElo" | "whiteElo" | "blackElo"
export type PositionQueryJs = { fen: string; type_: string }
export type PositionStats = { move: string; white: number; draw: number; black: number; unknown: number }
export type PositionSummary = { token: string; fingerprint: string; fen: string; total: number; openings: PositionStats[]; skippedGames: number; scanMs: number; cacheHit: boolean }
export type ProgressEvent = { id: string; progress: number; finished: boolean }
export type ProgressItem = { id: string; progress: number; finished: boolean }
export type Puzzle = { id: number; fen: string; moves: string; rating: number; rating_deviation: number; popularity: number; nb_plays: number }
export type PuzzleDatabaseInfo = { title: string; description: string; puzzleCount: number; storageSize: bigint; path: string }
export type QueryOptions<SortT> = { skipCount: boolean; page?: number | null; pageSize?: number | null; sort: SortT; direction: SortDirection }
export type QueryResponse<T> = { data: T; count: number | null }
export type ReportEloBand = { minElo: number; maxElo: number; results: ReportResults }
export type ReportFilters = { whitePlayer: number | null; blackPlayer: number | null; anyPlayer: number | null; whiteElo: [number, number] | null; blackElo: [number, number] | null; startDate: string | null; endDate: string | null; result: string | null }
export type ReportLine = { moves: string[]; fen: string; statistics: ReportStatistics; exampleOffset: number; example: PositionGameMetadata }
export type ReportMoveOrder = { startFen: string; moves: string[]; statistics: ReportStatistics; exampleOffset: number }
export type ReportPlayer = { id: number; name: string; games: number; whiteGames: number; blackGames: number; wins: number; draws: number; losses: number; unknown: number; averageElo: number | null; peakElo: number | null }
export type ReportResults = { white: number; draw: number; black: number; unknown: number }
export type ReportRoute = { moves: string[]; results: ReportResults; exampleOffset: number }
export type ReportStatistics = { results: ReportResults; averageWhiteElo: number | null; averageBlackElo: number | null; ratedWhite: number; ratedBlack: number }
export type ReportTransposition = { fen: string; ply: number; games: number; routeCount: number; routes: ReportRoute[] }
export type ReportYear = { year: number; results: ReportResults }
export type Score = { value: ScoreValue; 
/**
 * The probability of each result (win, draw, loss).
 */
wdl: [number, number, number] | null }
export type ScoreValue = 
/**
 * The score in centipawns.
 */
{ type: "cp"; value: number } | 
/**
 * Mate coming up in this many moves. Negative value means the engine is getting mated.
 */
{ type: "mate"; value: number }
export type Sides = "BlackWhite" | "WhiteBlack" | "Any"
export type SiteStatsData = { site: string; player: string; data: StatsData[] }
export type SortDirection = "asc" | "desc"
export type StatsData = { date: string; is_player_white: boolean; player_elo: number; result: GameOutcome; time_control: string; opening: string }
export type TimeControl = { initialTime: bigint; increment: bigint }
export type Token = { type: "ParenOpen" } | { type: "ParenClose" } | { type: "Comment"; value: string } | { type: "San"; value: string } | { type: "Header"; value: { tag: string; value: string } } | { type: "Nag"; value: string } | { type: "Outcome"; value: string }
export type TournamentQuery = { options: QueryOptions<TournamentSort>; name: string | null }
export type TournamentSort = "id" | "name"
/**
 * Represents a UCI option definition.
 */
export type UciOptionConfig = 
/**
 * The option of type `check` (a boolean).
 */
{ type: "check"; value: { 
/**
 * The name of the option.
 */
name: string; 
/**
 * The default value of this `bool` property.
 */
default: boolean | null } } | 
/**
 * The option of type `spin` (a signed integer).
 */
{ type: "spin"; value: { 
/**
 * The name of the option.
 */
name: string; 
/**
 * The default value of this integer property.
 */
default: bigint | null; 
/**
 * The minimal value of this integer property.
 */
min: bigint | null; 
/**
 * The maximal value of this integer property.
 */
max: bigint | null } } | 
/**
 * The option of type `combo` (a list of strings).
 */
{ type: "combo"; value: { 
/**
 * The name of the option.
 */
name: string; 
/**
 * The default value for this list of strings.
 */
default: string | null; 
/**
 * The list of acceptable strings.
 */
var: string[] } } | 
/**
 * The option of type `button` (an action).
 */
{ type: "button"; value: { 
/**
 * The name of the option.
 */
name: string } } | 
/**
 * The option of type `string` (a string, unsurprisingly).
 */
{ type: "string"; value: { 
/**
 * The name of the option.
 */
name: string; 
/**
 * The default value of this string option.
 */
default: string | null } }
export type WeightedOpeningLine = { moves: string[]; weight?: number; side?: OpeningLineSide }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
