/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as StudiesRouteImport } from './routes/studies'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FilesRouteImport } from './routes/files'
import { Route as EnginesRouteImport } from './routes/engines'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as DatabasesIndexRouteImport } from './routes/databases/index'
import { Route as TrainingTacticsRouteImport } from './routes/training/tactics'
import { Route as TrainingOpeningsRouteImport } from './routes/training/openings'
import { Route as TrainingLibraryRouteImport } from './routes/training/library'
import { Route as TrainingEndgamesRouteImport } from './routes/training/endgames'
import { Route as DatabasesDatabaseIdRouteImport } from './routes/databases/$databaseId'
import { Route as TrainingTacticsIndexRouteImport } from './routes/training/tactics/index'
import { Route as TrainingTacticsPracticeSetIdRouteImport } from './routes/training/tactics/practice/$setId'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesRoute = StudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesRoute = EnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingRoute,
} as any)
const DatabasesIndexRoute = DatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingTacticsRoute = TrainingTacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingOpeningsRoute = TrainingOpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingLibraryRoute = TrainingLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingEndgamesRoute = TrainingEndgamesRouteImport.update({
  id: '/endgames',
  path: '/endgames',
  getParentRoute: () => TrainingRoute,
} as any)
const DatabasesDatabaseIdRoute = DatabasesDatabaseIdRouteImport.update({
  id: '/databases/$databaseId',
  path: '/databases/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingTacticsIndexRoute = TrainingTacticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingTacticsRoute,
} as any)
const TrainingTacticsPracticeSetIdRoute =
  TrainingTacticsPracticeSetIdRouteImport.update({
    id: '/practice/$setId',
    path: '/practice/$setId',
    getParentRoute: () => TrainingTacticsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/engines': typeof EnginesRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/studies': typeof StudiesRoute
  '/training': typeof TrainingRouteWithChildren
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/training/endgames': typeof TrainingEndgamesRoute
  '/training/library': typeof TrainingLibraryRoute
  '/training/openings': typeof TrainingOpeningsRoute
  '/training/tactics': typeof TrainingTacticsRouteWithChildren
  '/databases/': typeof DatabasesIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/training/tactics/': typeof TrainingTacticsIndexRoute
  '/training/tactics/practice/$setId': typeof TrainingTacticsPracticeSetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/engines': typeof EnginesRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/studies': typeof StudiesRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/training/endgames': typeof TrainingEndgamesRoute
  '/training/library': typeof TrainingLibraryRoute
  '/training/openings': typeof TrainingOpeningsRoute
  '/databases': typeof DatabasesIndexRoute
  '/training': typeof TrainingIndexRoute
  '/training/tactics': typeof TrainingTacticsIndexRoute
  '/training/tactics/practice/$setId': typeof TrainingTacticsPracticeSetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/engines': typeof EnginesRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/studies': typeof StudiesRoute
  '/training': typeof TrainingRouteWithChildren
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/training/endgames': typeof TrainingEndgamesRoute
  '/training/library': typeof TrainingLibraryRoute
  '/training/openings': typeof TrainingOpeningsRoute
  '/training/tactics': typeof TrainingTacticsRouteWithChildren
  '/databases/': typeof DatabasesIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/training/tactics/': typeof TrainingTacticsIndexRoute
  '/training/tactics/practice/$setId': typeof TrainingTacticsPracticeSetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/engines'
    | '/files'
    | '/settings'
    | '/studies'
    | '/training'
    | '/databases/$databaseId'
    | '/training/endgames'
    | '/training/library'
    | '/training/openings'
    | '/training/tactics'
    | '/databases/'
    | '/training/'
    | '/training/tactics/'
    | '/training/tactics/practice/$setId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/engines'
    | '/files'
    | '/settings'
    | '/studies'
    | '/databases/$databaseId'
    | '/training/endgames'
    | '/training/library'
    | '/training/openings'
    | '/databases'
    | '/training'
    | '/training/tactics'
    | '/training/tactics/practice/$setId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/engines'
    | '/files'
    | '/settings'
    | '/studies'
    | '/training'
    | '/databases/$databaseId'
    | '/training/endgames'
    | '/training/library'
    | '/training/openings'
    | '/training/tactics'
    | '/databases/'
    | '/training/'
    | '/training/tactics/'
    | '/training/tactics/practice/$setId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  EnginesRoute: typeof EnginesRoute
  FilesRoute: typeof FilesRoute
  SettingsRoute: typeof SettingsRoute
  StudiesRoute: typeof StudiesRoute
  TrainingRoute: typeof TrainingRouteWithChildren
  DatabasesDatabaseIdRoute: typeof DatabasesDatabaseIdRoute
  DatabasesIndexRoute: typeof DatabasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies': {
      id: '/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof StudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/databases/': {
      id: '/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof DatabasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/tactics': {
      id: '/training/tactics'
      path: '/tactics'
      fullPath: '/training/tactics'
      preLoaderRoute: typeof TrainingTacticsRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/openings': {
      id: '/training/openings'
      path: '/openings'
      fullPath: '/training/openings'
      preLoaderRoute: typeof TrainingOpeningsRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/library': {
      id: '/training/library'
      path: '/library'
      fullPath: '/training/library'
      preLoaderRoute: typeof TrainingLibraryRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/endgames': {
      id: '/training/endgames'
      path: '/endgames'
      fullPath: '/training/endgames'
      preLoaderRoute: typeof TrainingEndgamesRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/databases/$databaseId': {
      id: '/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof DatabasesDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/tactics/': {
      id: '/training/tactics/'
      path: '/'
      fullPath: '/training/tactics/'
      preLoaderRoute: typeof TrainingTacticsIndexRouteImport
      parentRoute: typeof TrainingTacticsRoute
    }
    '/training/tactics/practice/$setId': {
      id: '/training/tactics/practice/$setId'
      path: '/practice/$setId'
      fullPath: '/training/tactics/practice/$setId'
      preLoaderRoute: typeof TrainingTacticsPracticeSetIdRouteImport
      parentRoute: typeof TrainingTacticsRoute
    }
  }
}

interface TrainingTacticsRouteChildren {
  TrainingTacticsIndexRoute: typeof TrainingTacticsIndexRoute
  TrainingTacticsPracticeSetIdRoute: typeof TrainingTacticsPracticeSetIdRoute
}

const TrainingTacticsRouteChildren: TrainingTacticsRouteChildren = {
  TrainingTacticsIndexRoute: TrainingTacticsIndexRoute,
  TrainingTacticsPracticeSetIdRoute: TrainingTacticsPracticeSetIdRoute,
}

const TrainingTacticsRouteWithChildren = TrainingTacticsRoute._addFileChildren(
  TrainingTacticsRouteChildren,
)

interface TrainingRouteChildren {
  TrainingEndgamesRoute: typeof TrainingEndgamesRoute
  TrainingLibraryRoute: typeof TrainingLibraryRoute
  TrainingOpeningsRoute: typeof TrainingOpeningsRoute
  TrainingTacticsRoute: typeof TrainingTacticsRouteWithChildren
  TrainingIndexRoute: typeof TrainingIndexRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingEndgamesRoute: TrainingEndgamesRoute,
  TrainingLibraryRoute: TrainingLibraryRoute,
  TrainingOpeningsRoute: TrainingOpeningsRoute,
  TrainingTacticsRoute: TrainingTacticsRouteWithChildren,
  TrainingIndexRoute: TrainingIndexRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  EnginesRoute: EnginesRoute,
  FilesRoute: FilesRoute,
  SettingsRoute: SettingsRoute,
  StudiesRoute: StudiesRoute,
  TrainingRoute: TrainingRouteWithChildren,
  DatabasesDatabaseIdRoute: DatabasesDatabaseIdRoute,
  DatabasesIndexRoute: DatabasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
